[[plugins]]
repo = 'Shougo/dein.vim'
hook_source = 'source ~/.vim/plugins/dein.rc.vim'
rts = ''

[[plugins]]
repo = 'tomasr/molokai'
hook_add = '''
  let g:molokai_original = 1
  let g:rehash256 = 1
'''

[[plugins]]
repo = 'KeitaNakamura/neodark.vim'
hook_add = '''
	let g:neodark#background = '#202020'
	let g:neodark#use_256color = 1
'''

[[plugins]]
repo = 'jacoborus/tender.vim'

[[plugins]]
repo = 'itchyny/vim-haskell-indent'

# molokaiのカッコの色を変える設定が壊れる。
# [[plugins]]
# repo = 'nathanaelkane/vim-indent-guides'
# hook_source = 'source ~/.vim/rc/plugins/vim-indent-guides.rc.vim'

[[plugins]]
repo = 'vim-jp/vimdoc-ja'
hook_source = 'set helplang=ja,en'

