[[plugins]]
repo = 'Shougo/dein.vim'
hook_source = 'source ~/.vim/plugins/dein.rc.vim'
rts = ''

[[plugins]]
repo = 'tomasr/molokai'
hook_add = '''
  let g:molokai_original = 1
  let g:rehash256 = 1
'''
script_type = 'colors'

[[plugins]]
repo = 'ErichDonGubler/vim-sublime-monokai'
hook_add = '''
  let g:sublimemonokai_term_italic = 1
'''
script_type = 'colors'

[[plugins]]
repo = 'vim-jp/vimdoc-ja'
hook_source = 'set helplang=ja,en'
